// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf

package runtime

// import "github.com/DataDog/datadog-agent/pkg/ebpf/bytecode/runtime"
var SharedLibraries = newAsset("shared-libraries.c", "db2c6f864df6ab67717efc775bf75f5a71f698b463900c8673870cbf04211ec1")
